spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: lb://serviceA
          predicates:
            - Path=/serviceA/**
        - id: serviceB
          uri: lb://serviceB
          predicates:
            - Path=/serviceB/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/